baseURL = 'https://isaacvicente.github.io'
languageCode = 'en-us'
title = 'Isaac Vicente'
theme = 'typo'

[taxonomies]
tag = 'tags'

[params]
# Meta description
description = "A Tech Blog"

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'Hi!'
homeIntroContent = """
I'm a Devops Engineer majoring in computer science at UFCG.  
I am interested in a range of topics, including algorithms, distributed systems, networking, and cloud.
"""

# Collection to display on home
homeCollectionTitle = 'Posts'
homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
[params.breadcrumbs]
enabled = true
showCurrentPage = true
home = "~"

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/isaac-vicente/"

# [[params.social]]
# name = "medium"
# url = "https://medium.com/@user"

[[params.social]]
name = "github"
url = "https://github.com/isaacvicente"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "about"
url = "/about"

[params.giscus]
enable = true
repo = "isaacvicente/isaacvicente.github.io"
repoid = "R_kgDOPbfbhw"
category = "Announcements"
categoryid = "DIC_kwDOPbfbh84Cvfdp"
mapping = "pathname"
theme = "preferred_color_scheme" 

# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'algol'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

defaultContentLanguage = 'en'
[languages]
  [languages.en]
    contentDir = 'content/en'
    languageName = 'English'
    weight = 1
  [languages.br]
    contentDir = 'content/br'
    languageName = 'Português'
    weight = 2
